config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :menuitems, except: [:destroy]
  resources :orders
  resources :cumstomers
  get 'welcome/index'
  resources :posts
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cumstomer.rb
class Cumstomer < ApplicationRecord
    has_many:orders
    has_many:menuitems, :through => :orders 
end

app/controllers/cumstomers_controller.rb
class CumstomersController < ApplicationController
  before_action :set_cumstomer, only: [:show, :edit, :update, :destroy]

  # GET /cumstomers
  # GET /cumstomers.json
  def index
    @cumstomers = Cumstomer.all
  end

  # GET /cumstomers/1
  # GET /cumstomers/1.json
  def show
  end

  # GET /cumstomers/new
  def new
    @cumstomer = Cumstomer.new
  end

  # GET /cumstomers/1/edit
  def edit
  end

  # POST /cumstomers
  # POST /cumstomers.json
  def create
    @cumstomer = Cumstomer.new(cumstomer_params)

    respond_to do |format|
      if @cumstomer.save
        format.html { redirect_to @cumstomer, notice: 'Cumstomer was successfully created.' }
        format.json { render :show, status: :created, location: @cumstomer }
      else
        format.html { render :new }
        format.json { render json: @cumstomer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cumstomers/1
  # PATCH/PUT /cumstomers/1.json
  def update
    respond_to do |format|
      if @cumstomer.update(cumstomer_params)
        format.html { redirect_to @cumstomer, notice: 'Cumstomer was successfully updated.' }
        format.json { render :show, status: :ok, location: @cumstomer }
      else
        format.html { render :edit }
        format.json { render json: @cumstomer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cumstomers/1
  # DELETE /cumstomers/1.json
  def destroy
    @cumstomer.destroy
    respond_to do |format|
      format.html { redirect_to cumstomers_url, notice: 'Cumstomer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cumstomer
      @cumstomer = Cumstomer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cumstomer_params
      params.require(:cumstomer).permit(:customerID, :name, :surename)
    end
end

app/helpers/cumstomers_helper.rb
module CumstomersHelper
end

app/views/cumstomers/_form.html.erb
<%= form_with(model: cumstomer, local: true) do |form| %>
  <% if cumstomer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cumstomer.errors.count, "error") %> prohibited this cumstomer from being saved:</h2>

      <ul>
      <% cumstomer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customerID %>
    <%= form.number_field :customerID, id: :cumstomer_customerID %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cumstomer_name %>
  </div>

  <div class="field">
    <%= form.label :surename %>
    <%= form.text_field :surename, id: :cumstomer_surename %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cumstomers/edit.html.erb
<h1>Editing Cumstomer</h1>

<%= render 'form', cumstomer: @cumstomer %>

<%= link_to 'Show', @cumstomer %> |
<%= link_to 'Back', cumstomers_path %>

app/views/cumstomers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cumstomers</h1>

<table>
  <thead>
    <tr>
      <th>Customerid</th>
      <th>Name</th>
      <th>Surename</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cumstomers.each do |cumstomer| %>
      <tr>
        <td><%= cumstomer.customerID %></td>
        <td><%= cumstomer.name %></td>
        <td><%= cumstomer.surename %></td>
        <td><%= link_to 'Show', cumstomer %></td>
        <td><%= link_to 'Edit', edit_cumstomer_path(cumstomer) %></td>
        <td><%= link_to 'Destroy', cumstomer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cumstomer', new_cumstomer_path %>

app/views/cumstomers/new.html.erb
<h1>New Cumstomer</h1>

<%= render 'form', cumstomer: @cumstomer %>

<%= link_to 'Back', cumstomers_path %>

app/views/cumstomers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customerid:</strong>
  <%= @cumstomer.customerID %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cumstomer.name %>
</p>

<p>
  <strong>Surename:</strong>
  <%= @cumstomer.surename %>
</p>

<%= link_to 'Edit', edit_cumstomer_path(@cumstomer) %> |
<%= link_to 'Back', cumstomers_path %>