config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :menuitems, except: [:destroy]
  resources :orders
  resources :cumstomers
  get 'welcome/index'
  resources :posts
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menuitem.rb
class Menuitem < ApplicationRecord
    has_many:orders
    has_many:cumstomers, :through => :orders
    
    def self.search(search)
        if search
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/controllers/menuitems_controller.rb
class MenuitemsController < ApplicationController
  before_action :set_menuitem, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /menuitems
  # GET /menuitems.json
  def index
    @menuitems = Menuitem.search(params[:search])
  end

  # GET /menuitems/1
  # GET /menuitems/1.json
  def show
  end

  # GET /menuitems/new
  def new
    @menuitem = Menuitem.new
  end

  # GET /menuitems/1/edit
  def edit
  end

  # POST /menuitems
  # POST /menuitems.json
  def create
    @menuitem = Menuitem.new(menuitem_params)

    respond_to do |format|
      if @menuitem.save
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully created.' }
        format.json { render :show, status: :created, location: @menuitem }
      else
        format.html { render :new }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menuitems/1
  # PATCH/PUT /menuitems/1.json
  def update
    respond_to do |format|
      if @menuitem.update(menuitem_params)
        format.html { redirect_to @menuitem, notice: 'Menuitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @menuitem }
      else
        format.html { render :edit }
        format.json { render json: @menuitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menuitems/1
  # DELETE /menuitems/1.json
  def destroy
    @menuitem.destroy
    respond_to do |format|
      format.html { redirect_to menuitems_url, notice: 'Menuitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menuitem
      @menuitem = Menuitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menuitem_params
      params.require(:menuitem).permit(:menuitemID, :name, :price, :description)
    end
end

app/helpers/menuitems_helper.rb
module MenuitemsHelper
end

app/views/menuitems/_form.html.erb
<%= form_with(model: menuitem, local: true) do |form| %>
  <% if menuitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menuitem.errors.count, "error") %> prohibited this menuitem from being saved:</h2>

      <ul>
      <% menuitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :menuitemID %>
    <%= form.number_field :menuitemID, id: :menuitem_menuitemID %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :menuitem_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :menuitem_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :menuitem_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menuitems/edit.html.erb
<h1>Editing Menuitem</h1>

<%= render 'form', menuitem: @menuitem %>

<%= link_to 'Show', @menuitem %> |
<%= link_to 'Back', menuitems_path %>

app/views/menuitems/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Menuitems</h2>

<table class = "table table-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Menuitemid</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menuitems.each do |menuitem| %>
      <tr>
        <td><%= menuitem.menuitemID %></td>
        <td><%= menuitem.name %></td>
        <td><%= menuitem.price %></td>
        <td><%= menuitem.description %></td>
        <td><%= link_to 'Show', menuitem %></td>
        <%# sementara hapus edit dan destroy dulu %>
        <% if user_signed_in?%>
         <td><%= link_to 'Edit', edit_menuitem_path(menuitem) %></td> 
         <td><%= link_to 'Destroy', menuitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menuitem', new_menuitem_path %>

app/views/menuitems/new.html.erb
<h1>New Menuitem</h1>

<%= render 'form', menuitem: @menuitem %>

<%= link_to 'Back', menuitems_path %>

app/views/menuitems/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to "Home", welcome_index_path%>
<p>
  <strong>Menuitemid:</strong>
  <%= @menuitem.menuitemID %>
</p>

<p>
  <strong>Name:</strong>
  <%= @menuitem.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menuitem.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menuitem.description %>
</p>

<%= link_to 'Edit', edit_menuitem_path(@menuitem) %> |
<%= link_to 'Back', menuitems_path %>